### PR TITLE
DM-33034: move GraphViz dot utilities to pipe_base

### PR DESCRIPTION
**Pull request by TallJimbo**
## Checklist

- [ ] ran Jenkins
- [ ] added a release note for user-visible changes to `doc/changes`

This PR is based on a temporary branch because its merge is blocked by DM-33027 (mostly because of changes in pipe_base, rather than here, but it's easier to keep things in sync this way).  I'll rebase once DM-33027 lands.

Nothing to see here but code removal; that code reappears in the [pipe_base PR for this ticket](https://github.com/lsst/pipe_base/pull/222).

### CODE REVIEW

**Comment by timj** [comment]
#158 did merge so does that mean we can now rebased this PR on main?

**Comment by TallJimbo** [comment]
Yes, we can rebase now but I think conflicts are more likely than not.

**Comment by timj** [comment]
Rebase of this one was easy.

**Comment by timj** [comment]
(although one of the commits here seems out of place -- the expanded pipeline one)

**Comment by timj** [comment]
I see that in lsst/pipe_base#222 you state that the expanded pipeline part of the PR disappeared so maybe we drop that commit? I also see though that the pipe_base PR is quite large and is more than simply relocating dotTools. How about I move dotTools on a different ticket and then close this PR (dropping the expanded pipeline commit)?

**Comment by TallJimbo** [comment]
Moving dotTools on a different ticket and then closing this PR sounds great.  I don't really care about the pipe_base PR for this ticket either, but I do want to keep the pipe_base branch, as it's got useful stuff along with a lot of no-longer-useful stuff.

**Comment by timj** [comment]
This is made obsolete by #300

**Pull request closed without merging**
