### PR TITLE
DM-10351: Add logging messages to track task execution progress

### PR DESCRIPTION
**Pull request by andy-slac**
Two messages are now printed when task finishes execution - wall clock
time for task execution and count of tasks finished/failed and still to
be executed.

### CODE REVIEW

**Review by timj — APPROVED** [review]

**Comment by timj** [comment]
@andy-slac feel free to switch the package to github actions whilst you are at it (lint.yaml from daf_butler should be fine).

**Comment by ktlim** [comment]
Better than stealing from daf_butler is choosing "LSST DM Python lint Workflow" from the "Actions" tab (and then removing `.travis.yml`).

**Comment by andy-slac** [comment]
I switched to actions. seems to be working OK. Do I also need to delete webhook for travis?

**Comment by timj** [comment]
Yes, need to switch the CI check to lint and disable the travis requirement.

**Comment by andy-slac** [comment]
That I have done already, otherwise "Merge" button was disabled. There is still a webhooks option for travis, I think I should delete that too?
Screenshot_2020-11-11 lsst ctrl_mpexec

**Comment by timj** [comment]
I think you can ignore those.

**Pull request merged**
